pretrain_exploit_exp_name: exploit_pretrain
exploit_exp_name: exploit
pretrain: true
train: true

# load checkpoints
gvae_exp_name: gvae

# data
dataset_name: shapenet_car_above
scenes_range_start: 480
n_scenes: 40

eval:
  video:
    n_scenes: 40 #number of different scenes to vizualize
  metrics:
    n_scenes: 40 #number of scenes to calculte the metrics upon
    log_scenes_independently: true


global_latent_nerf:
  apply: true
  random_init: false
  n_base: 50
  n_global_features: 22
  n_local_features: 10

pretrain_args:
  n_epochs: 50
  batch_size: 32 
  
  cache_latents: 
    batch_size: 32 # 512 on A100

  eval_metrics_every_epoch: 3
  eval_video_every_epoch: 3
  save_every_epoch: 1

train_args:
  n_epochs: 50
  batch_size: 32

  eval_metrics_every_epoch: 3
  eval_video_every_epoch: 3
  save_every_epoch: 1