#---- CONFIG FOR EXPLOTATION PHASE ----- 

# ---meta---
exploit_exp_name: exploit_default
pretrain_exploit_exp_name: exploit_pretrain_default
pretrain: true
train: true
rgb_override: false

# load checkpoints
gvae_exp_name: gvae_default 
gvae_savedir: outputs

# data
dataset_name: shapenet_car_above
scenes_range_start: 1000
n_scenes: 10  
rgb_img_size: 128


eval:
  video:
    n_scenes: 10 #number of different scenes to vizualize
    n_frames: 40
    fps: 10
    azimuth_range: [0, 1]
    elevation_range: [0.3, 0.3]
    radius_range: [1.3, 1.3]
  metrics:
    n_scenes: 10 #number of scenes to calculte the metrics upon
    log_scenes_independently: true

# triplane
latent_nerf: 
  mu_nerf: false # if true, we don't sample from the latent distrib but we use the mean
  concat_low_res_rgb: false # if true, we concatenate the low res rgb img to the latent img
  n_concat_channels: 3 # only relevant if concat_low_res_rgb is true
  n_latent_channels: 4
  img_size: 16
  n_local_features: 32
  triplane_resolution: 64
  aggregation_mode: sum
  rendering_options:
    disparity_space_sampling: false
    clamp_mode: softplus
    depth_resolution: 48
    depth_resolution_importance: 48
    ray_start: 0.5
    ray_end: 2.1
    box_warp: 2

global_latent_nerf:
  apply: false
  random_init: false # option specific to exploit script, so as not to load global planes from gvae training
  n_base: 25
  n_global_features: 22
  n_local_features: 10
  fusion_mode: concat # either 'concat' or 'sum'.
  bias: true

# pretraining
pretrain_args:
  warmup_window: false
  losses: # encode nerf by default
    loss_alpha_d: False
    loss_ae: False
    loss_lnerf: True
    loss_low_res_rgb: False # True has effect only if concat_low_res_rgb is True
    loss_rgb_override: False # rgb override.

  freezes: # do not change
    freeze_decoder: True
    freeze_encoder: True
    freeze_lnerf: False
    freeze_base_coefs: False
    freeze_global_lnerf: False

  #optim
  wandb_note: pretraining
  n_epochs: 50 
  tinymlp_random_init: true
  freeze_tinymlp_after_n_epoch : -1
  batch_size: 16

  cache_latents: 
    apply: true
    use_mean: true
    batch_size: 64

  scheduler: #TODO: add this per module
    type: 'exp' #either 'exp' or 'multistep'
    exp_config:
      gamma: 0.94157
    multistep_config:
      milestones: [20, 40]
      gamma: 0.3

  encoder:
    lr: 1.e-4
  decoder:
    lr: 1.e-4
  latent_nerf:
    lr: 1.e-2
    tinymlp_lr: 1.e-2
  global_latent_nerf:
    lr: 1.e-2
  base_coefs:
    lr: 1.e-2

  lambda_ae: 0.1
  lambda_latent_nerf: 1
  lambda_alpha_D: 1
  lambda_low_res_rgb: 1
  lambda_kl: 0
  lambda_tv: 0
  tv_mode: 'l2' #either 'l2' or 'l1'
  lambda_depth_tv: 0
  depth_tv_mode: 'l2' #either 'l2' or 'l1'

  # logging
  log_sw_stats_every_iter: 10
  log_training_metrics_every_epoch: 1 
  eval_metrics_every_epoch: 1
  eval_video_every_epoch: 1
  save_every_epoch: 1
  save_latest_only : true

# training
train_args:
  warmup_window: false
  losses:
    loss_alpha_d: True
    loss_ae: False
    loss_lnerf: False
    loss_low_res_rgb: False # True has effect only if concat_low_res_rgb is True
    loss_rgb_override: False # rgb override
    
  freezes:
    freeze_decoder: False
    freeze_encoder: True
    freeze_lnerf: False
    freeze_base_coefs: False
    freeze_global_lnerf: False
    
  #optim
  wandb_note: training
  n_epochs: 50
  freeze_tinymlp_after_n_epoch : -1
  batch_size: 16

  cache_latents: 
    apply: true
    use_mean: true
    batch_size: 64

  scheduler: 
    type: 'exp' #either 'exp' or 'multistep'
    exp_config:
      gamma: 0.94157
    multistep_config:
      milestones: [20, 40]
      gamma: 0.3

  encoder:
    lr: 1.e-4
  decoder:
    lr: 1.e-4
  latent_nerf:
    lr: 1.e-3
    tinymlp_lr: 1.e-3
  global_latent_nerf:
    lr: 1.e-2
  base_coefs:
    lr: 1.e-2

  lambda_ae: 0.1
  lambda_latent_nerf: 1
  lambda_alpha_D: 1
  lambda_low_res_rgb: 1
  lambda_kl: 0
  lambda_tv: 0
  tv_mode: 'l2' #either 'l2' or 'l1'
  lambda_depth_tv: 0
  depth_tv_mode: 'l2' #either 'l2' or 'l1'

  # logging
  log_sw_stats_every_iter: 10
  log_training_metrics_every_epoch: 1
  eval_metrics_every_epoch: 1
  eval_video_every_epoch: 1
  save_every_epoch: 1
  save_latest_only : true


# other
wandb_project_name: gvae
savedir: outputs